// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID    int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string  `gorm:"column:name;not null" json:"name"`
	Phone *string `gorm:"column:phone" json:"phone"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
